name: large-timer
channels:
  - pytorch
  - conda-forge
  # - pytorch
  - defaults
dependencies:
 - python==3.10
 - pandas==1.5.3
 - scikit-learn==1.2.2
 - numpy==1.23.5
 - matplotlib==3.7.0
 - einops==0.4.0
 - numpy==1.23.5
 - patool==1.12
 - scipy==1.10.1
 - sktime==0.16.1
 - sympy==1.11.1
 - tqdm==4.64.1
 - transformers==4.40.1
 - pip
#  - pip:
#  - torch==2.0.0
 - pytorch=2.5.0
#  - pip:
#    - reformer-pytorch==1.4.4
